name: Phoenix Core Builder

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu Çek
      uses: actions/checkout@v4

    - name: ARM Derleyicisini Kur
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-linux-gnueabi zip

    - name: Anka OS Çekirdeğini Derle
      run: |
        arm-linux-gnueabi-gcc -static -Os core/boot.c -o anka_os.bin

    - name: Kendi Açık Kaynak Kurulum Motorumuzu Hazırla
      run: |
        # Klasör iskeletini kur
        mkdir -p Anka_ROM/META-INF/com/google/android
        mkdir -p Anka_ROM/system/bin
        
        # Derlediğimiz Anka OS çekirdeğini klasöre yerleştir
        cp anka_os.bin Anka_ROM/system/bin/anka_os
        
        # Kendi UPDATE-BINARY Motorumuzu Yazıyoruz (Saf Açık Kaynak)
        cat << 'EOF' > Anka_ROM/META-INF/com/google/android/update-binary
        #!/sbin/sh
        # ANKA OS KURULUM MOTORU
        
        OUTFD=$2
        ZIPFILE=$3
        
        # TWRP Ekranına Yazı Basma Fonksiyonumuz
        ui_print() {
          echo -n -e "ui_print $1\n" > /proc/self/fd/$OUTFD
          echo -n -e "ui_print\n" > /proc/self/fd/$OUTFD
        }
        
        ui_print "================================================="
        ui_print "             [ ANKA OS UYANIYOR... ]             "
        ui_print "================================================="
        ui_print "Gelistirici: Emre Burak"
        ui_print "Lisans: %100 Acik Kaynak (Open Source)"
        ui_print "Felsefe: Sifir Cihaz Yorgunlugu, Saf Performans."
        ui_print "Hedef: Cekmecedeki Telefonlari YZ Canavarina Cevirmek."
        ui_print "-------------------------------------------------"
        
        ui_print "[1/3] Sisteme Siziliyor..."
        # Cihazın sistemini hafızaya al
        mount /system
        
        ui_print "[2/3] Android Zombi Dosyalari Kaziniyor..."
        # Cihazdaki tüm eski Android kalıntılarını sil (Evrensel Kod)
        rm -rf /system/*
        
        ui_print "[3/3] Sinek Cekirdege Enjekte Ediliyor..."
        # Bizim ZIP'in içindeki dosyaları cihazın beynine çıkar
        unzip -o "$ZIPFILE" "system/*" -d /
        
        # Sinek'e çalıştırma yetkisi ver
        chmod 0755 /system/bin/anka_os
        
        # Sistemi kapat ve korumaya al
        umount /system
        
        ui_print "================================================="
        ui_print "KURULUM TAMAMLANDI! CIHAZA YENI BIR RUH VERDIN."
        EOF
        
        # Dosyayı motor olarak çalıştırılabilir hale getir
        chmod +x Anka_ROM/META-INF/com/google/android/update-binary
        
        # Hepsini tek bir flashlanabilir ZIP dosyasında paketle
        cd Anka_ROM
        zip -r ../Anka_OS_Kurulum.zip .
        cd ..

    - name: Sistemi İndirmeye Sun
      uses: actions/upload-artifact@v4
      with:
        name: Anka_OS_TWRP_ROM
        path: Anka_OS_Kurulum.zip
